sudo: required
services:
  - docker
before_install:
  - docker build -t nuxt-docker .
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "nuxt-docker"
  env: "NuxtDocker-env"
  bucket_name: "elasticbeanstalk-us-east-1-589538688281"
  bucket_path: "nuxt-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY